import os
import moviepy.editor as mp
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Replace with your API token from BotFather
TELEGRAM_BOT_TOKEN = "5707293090:AAHGLlHSx101F8T1DQYdcb9_MkRAjyCbt70"
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

# YouTube authentication
def youtube_authenticate():
    creds = None
    if os.path.exists("token.json"):
        creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("client_secret.json", SCOPES)
            creds = flow.run_local_server(port=0)
        with open("token.json", "w") as token:
            token.write(creds.to_json())
    return build("youtube", "v3", credentials=creds)

# Combine audio and image into a video
def combine_audio_image(image_path, audio_path, output_path):
    image_clip = mp.ImageClip(image_path)
    audio_clip = mp.AudioFileClip(audio_path)
    video = image_clip.set_duration(audio_clip.duration).set_audio(audio_clip)
    video.write_videofile(output_path, fps=24)

# YouTube video upload
def upload_to_youtube(video_file, title="Uploaded Video", description="Uploaded by bot", tags=None):
    youtube = youtube_authenticate()
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": "22"  # Category: People & Blogs
        },
        "status": {
            "privacyStatus": "public"
        }
    }
    media = MediaFileUpload(video_file, chunksize=-1, resumable=True)
    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )
    response = request.execute()
    return response

# Handlers for the Telegram bot
def start(update, context):
    update.message.reply_text("Send me an image and an audio file, and I'll combine them into a video and upload it to YouTube!")

# Storing the files
user_data = {}

def handle_photo(update, context):
    file = update.message.photo[-1].get_file()
    file_path = f"{update.message.from_user.id}_image.jpg"
    file.download(file_path)
    user_data['image'] = file_path
    update.message.reply_text("Image received! Now send me an audio file.")

def handle_audio(update, context):
    file = update.message.audio.get_file()
    file_path = f"{update.message.from_user.id}_audio.mp3"
    file.download(file_path)
    user_data['audio'] = file_path
    update.message.reply_text("Audio received! Now combining...")

    # Check if both files are received
    if 'image' in user_data and 'audio' in user_data:
        video_path = f"{update.message.from_user.id}_video.mp4"
        combine_audio_image(user_data['image'], user_data['audio'], video_path)
        
        update.message.reply_text("Uploading video to YouTube...")
        response = upload_to_youtube(video_path, title="Bot Video", description="Generated by Telegram bot")

        update.message.reply_text(f"Video uploaded! You can view it here: https://www.youtube.com/watch?v={response['id']}")

        # Clean up files
        os.remove(user_data['image'])
        os.remove(user_data['audio'])
        os.remove(video_path)

# Main function to run the bot
def main():
    updater = Updater(TELEGRAM_BOT_TOKEN, use_context=True)
    dp = updater.dispatcher

    dp.add_handler(CommandHandler("start", start))
    dp.add_handler(MessageHandler(Filters.photo, handle_photo))
    dp.add_handler(MessageHandler(Filters.audio, handle_audio))

    updater.start_polling()
    updater.idle()

if __name__ == "__main__":
    main()
